services:
  mqtt-addon:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: Synthia-MQTT
    restart: unless-stopped
    env_file:
      - ./runtime.env
    volumes:
      - ../../desired.json:/state/desired.json
      - ../../runtime.json:/state/runtime.json
      - ./docker-compose.yml:/orchestrator/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "18080:8080"
